### ISSUE TITLE
Config file should be named 50-kata.conf

### ISSUE THREAD

**Issue by andreaskaris** [harche/kata-operator#33]
Config file should be named 50-kata.conf

[root@openshift-worker-2 ~]# ls /etc/crio/crio.conf.d/
00-default  kata-50.conf

**Comment by jensfr** [comment]
Thanks for reporting this Andreas, I'll fix it

**Comment by fidencio** [comment]
Andreas, thanks for the issue report. Jens, thanks for the patch!

As it's been already fixed, I'll close this issue. Please, feel free to re-open it in case you feel need to do so.
